### PR TITLE
fixed webkit not found error

### PR DESCRIPTION
**Pull request by life1347**
This PR fixed the error that failed to find webkit framework on macOs 10.12.3 with Xcode 8.2.1 (8C1002)

```
# github.com/murlokswarm/mac
In file included from ../../../mac/window.go:4:
./window.h:5:9: fatal error: 'WebKit/Webkit.h' file not found
#import <WebKit/Webkit.h>
        ^
1 error generated.
```

### CODE REVIEW

**Comment by maxence-charriere** [comment]
Thank you @life1347
